### ISSUE TITLE
row.original gives type error

### ISSUE THREAD

**Issue by amorfati254** [bryanmylee/svelte-headless-table#112]
In every row i want to add a link that uses the original value id. this is important as am using the id as route param. however we I try to access the row.original I get type error.
```
<tbody {...$tableBodyAttrs}>
	{#each $rows as row (row.id)}
		<Subscribe rowAttrs={row.attrs()} let:rowAttrs>
			<tr {...rowAttrs}>
				{#each row.cells as cell (cell.id)}
					<Subscribe attrs={cell.attrs()} let:attrs>
						<td class="font-bold" {...attrs}>
							<Render of={cell.render()} />
						</td>
					</Subscribe>
				{/each}
				<td class="font-bold">
				   <a
				      href="properties/{row.original.id}"
				      class="btn btn-sm variant-filled-primary">
				      Details
				  </a>
				</td>
			</tr>
		</Subscribe>
	{/each}
</tbody>

```
I get the following error: "Property 'original' does not exist on type 'BodyRow<{ available_units: number | null; id: number | null; location: string | null; name: string | null; property_type: string | null; rental_price: number | null; total_units: number | null; }, { ...; }>'.",
However, when I log the row object it shows it has original property.

**Comment by amorfati254** [comment]
I found solution. I need to check if row.isData() before being able to access original.

**Comment by NiklasKK** [comment]
I tried the check with if but it does not work for me any ideas what I'm doing wrong here?
It still gives me the error:
`Property 'original' does not exist on type 'BodyRow<LdapMember, { sort: TablePlugin<any, SortByState<any>, SortByColumnOptions, SortByPropSet>; }>'.ts(2339)`

```svelte
<tbody {...$tableBodyAttrs}>
	{#each $rows as row (row.id)}
		<Subscribe rowAttrs={row.attrs()} let:rowAttrs>
			<tr {...rowAttrs} class="text-start">
			        <!-- isData() check here -->
				{#if row.isData()}
					<td class="p-0 m-0">
						<button
							type="button"
							class="btn btn-sm btn-success w-auto"
							on:click={() => addMember(row.original)}>Add</button
						></td>
				{/if}
				{#each row.cells as cell (cell.id)}
					<Subscribe attrs={cell.attrs()} let:attrs>
						<td {...attrs}>
							<Render of={cell.render()} />
						</td>
					</Subscribe>
				{/each}
			</tr>
		</Subscribe>
	{/each}
</tbody>
```

![image](https://github.com/bryanmylee/svelte-headless-table/assets/60063815/2215526e-9276-454d-989c-a04dc5108220)

**Comment by Nicicalu** [comment]
@NiklasKK Did you try doing the check inline? I did it like so:
```
href={row.isData() ? `/${row.original.event_id}`: "#"}
```

**Comment by NiklasKK** [comment]
> @NiklasKK Did you try doing the check inline? I did it like so:
> 
> ```
> href={row.isData() ? `/${row.original.event_id}`: "#"}
> ```

Okay, yeah when I change it to inline the error disappears. Guess it's more an error of Svelte then.
