### ISSUE TITLE
Make id optional

### ISSUE THREAD

**Issue by risalfajar** [bryanmylee/svelte-headless-table#114]
Can we just make `id` in `table.column()` with function accessor and `table.display()` optional? Since `header` is already unique in most cases, we can use that as default value for `id`.

**Comment by bryanmylee** [comment]
The only issue is that `id` needs to be unique because it's used for tracking columns within each group and column ordering / hiding.

`header` is unique in most cases, but it's also possible to have a non-text header. If we make `id` optional, we'd have to add a lot of complexity to the system.

**Comment by risalfajar** [comment]
Wouldn't adding more checks in `DataColumn` constructor suffice?

Something like:
```typescript
	constructor({
		header,
		footer,
		plugins,
		cell,
		accessor,
		id,
	}: DataColumnInit<Item, Plugins, Id, Value>) {
		super({ header, footer, plugins, id: 'Initialization not complete' });
		this.cell = cell;
		if (accessor instanceof Function) {
			this.accessorFn = accessor;
		} else {
			this.accessorKey = accessor;
		}
		if (id === undefined && this.accessorKey === undefined && header === undefined) {
			throw new Error('A column id or string accessor or header is required');
		}
		this.id = (id ?? String(this.accessorKey) ?? String(header)) as Id;
	}
```

**Comment by bryanmylee** [comment]
That could work! Unfortunately, I've been extremely busy so this project has been on the back-burner for me.

Could you help open a PR for it? I would love to merge any PR you have if you could provide one.
