### ISSUE TITLE
Consider adding a lessThan() to sorting plugin

### ISSUE THREAD

**Issue by sledgehammer999** [bryanmylee/svelte-headless-table#115]
**Disclaimer:** I am a C++ developer. I am currently playing around with typescript+svelte as a **hobby**. Aka a noob on these 2 technologies.

I was looking into this project to see if it will fit my table needs.
As I was reading the docs on the sorting plugin I realized it is kinda simple on exposed features.
The sorting function expected in `getSortValue` is too simple.

I am proposing of adding the "lessThan" approach used by Qt and the C++ std library:
The user/developer provides a function with this signature:
```ts
let lessThan:? (left: DataBodyCell, right: DataBodyCell) => boolean

// with a default implemenation of
(left, right) => (left.value < right.value)
```

The usage of `DataBodyCell` as the type is important for the second enhancement I had in mind:
Sometimes you might need to do a more complex sorting. What if the 2 compared cells in the row are equal? It would be nice to be able to look at their sibling cell in another column and use those values to sort (in my custom sorting function).

**Comment by sledgehammer999** [comment]
Basically let us provide our own compare function to be plugged in here:
https://github.com/bryanmylee/svelte-headless-table/blob/bc2e096117a773f0b0a6f960dc2ab59d48739e2d/src/lib/plugins/addSortBy.ts#L114

If `a` and `b` are of type `DataBodyCell` then the custom compare function should be provided on the model/table level IMO.

**Comment by bryanmylee** [comment]
Hey thanks for the suggestion @sledgehammer999, I would love to merge any PR you have if you could provide one.

Unfortunately, I've been extremely busy so this project has been on the back-burner for me.

**Comment by bryanmylee** [comment]
@sledgehammer999 Also, I just completely forgot to mention that you could have always done this with the [`getSortValue`](https://svelte-headless-table.bryanmylee.com/docs/plugins/add-sort-by#getsortvalue-value-string-number-string-number) function which I think is much more powerful.

```ts
const data = readable([
  { name: { first: 'Sam', last: 'Smith' } },
  { name: { first: 'Doja', last: 'Cat' } },
  { name: { first: 'Harry', last: 'Styles' } },
  { name: { first: 'Ariana', last: 'Grande' } },
]);

const table = createTable(data, {
  sort: addSortBy(),
});

const columns = table.createColumns([
  table.column({
    header: 'Name',
      accessor: 'name',
      plugins: {
        sort: {
          getSortValue(name) {
            // sorts by `name.first`, and if it matches then sort
            // by `name.last`.
            return [name.first, name.last];
          }
        }
      }
    }),
  }),
]);
```
