### ISSUE TITLE
[Suggestion] Easier way to CRUD and to get selectedRow data

### ISSUE THREAD

**Issue by piperun** [bryanmylee/svelte-headless-table#119]
Right now you have to rely on something akin to:
```js
const tableData = writable(data);

function deleteData() {
 $tableData.pop()
}
function addData() {
 $tableData.append(//...)
}
```
And with select into the mix, it's even more awkward to perform CRUD

I essentially wish that it was a lot more seamless (as is the case with say, tabulator).
Where it has add, remove, update built-in[1]

[1]https://tabulator.info/docs/5.4/update

**Comment by bryanmylee** [comment]
Sorry, I'm not quite sure what the proposed API would be like. Unfortunately, Svelte's reactivity does require a reassignment, so `pop` and `append` shouldn't work if I'm not mistaken?

**Comment by piperun** [comment]
My bad, I was thinking more that svelte-headless-table could have helper functions to add/remove/update the table, which is something tabulator has for instance.
Since as of right now, the solution I've done is using`pop` & `append` the `$tableData` array.

However I can understand if this is not desirable if svelte-headless-table is trying to be as close to tanstack table as possible (or at least svelte-headless-table feels a lot similar to tanstack tables 😄)

**Comment by bryanmylee** [comment]
Yep! Svelte Headless Table was heavily inspired by Tanstack and similarly, believes in keeping the `$data` prop as the single source of truth.
