### ISSUE TITLE
multiple data export formats

### ISSUE THREAD

**Issue by infinitebugs32** [bryanmylee/svelte-headless-table#128]
Hi there,

Not sure if I'm missing something here:
The documentation tells us how to specify a format for exporting the data of the table:
```
let table = createTable(tableSource, {
        export: addDataExport({format: 'json'}),
});
```
But how do I do if I want 2 possibilities of exporting ? Let's say, I have two buttons. One for exporting in JSON and one for exporting in CSV. I need to be able to dynamically tell my table that the export format is changing accordingly to the button pressed, without re-creating or reloading the table.

Thanks a lot

**Comment by bryanmylee** [comment]
The recommended solution is to use two data export plugins!

```ts
let table = createTable(tableSource, {
  jsonExport: addDataExport({format: 'json'}),
  csvExport: addDataExport({format: 'csv'}),
});
```
