### ISSUE TITLE
Is createRender support slot ?

### ISSUE THREAD

**Issue by oktapascal** [bryanmylee/svelte-headless-table#137]
Is function `createRender` support `slots` ?

for example I have an `Actions` component like this.

Actions.svelte
`<div class="dropdown">
        <button
            class="btn btn-icon"
            type="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
            title="Actions Data"
        >
            <i class="bi bi-three-dots-vertical" />
        </button>
        <ul class="dropdown-menu table-actions">
            <slot />
        </ul>
    </div>`

my expectation is that I can use it in this way in the components table
Table.svelte
`createRender(<Actions><li>action 1</li><li>action 2</li></Actions>)`

**Comment by lolcabanon** [comment]
According to the [svelte-render doc](https://github.com/bryanmylee/svelte-render) :

><Render /> handles props and automatically registers the event handlers defined with .on as well as slot data defined with .slot.

So you can do `createRender(Actions, props).slot("<li>action 1</li><li>action 2</li>")`.

Just tested it and `it works™`!

**Comment by oktapascal** [comment]
I'm relieved my problem was noticed. Thanks for the solution, you're great!
