### ISSUE TITLE
Svelte Headless Table uses stores for reactivity. You need to update that store whenever the page data changes to inform Svelte Headless Table of the data change.

### ISSUE THREAD

**Issue by Tihomir971** [bryanmylee/svelte-headless-table#152]
Svelte Headless Table uses stores for reactivity. You need to update that store whenever the page data changes to inform Svelte Headless Table of the data change.

It's an unfortunate consequence of Svelte's separation between component reactivity (`$:`) and external tooling reactivity (stores).

```ts
<script lang="ts">
  export let data;
  const manufacturers = writable(data.manufacturers);
  // Update the data store whenever `data` changes.
  $: $manufacturers = data.manufacturers;
  
  const table = createTable(manufacturers, {...});
  // ...
</script>
```

_Originally posted by @bryanmylee in https://github.com/bryanmylee/svelte-headless-table/discussions/105#discussioncomment-4928758_

**Comment by Tihomir971** [comment]
I have reactive table, but i have problem with menu column:
`		table.column({
			header: createRender(CarbonMenu, {
				width: '20',
				height: '20'
			}),
			accessor: (item) => item.id,
			cell: ({ value }) =>
				createRender(CarbonOverflowMenuHorizontal)
                                .on('click', async () => {
					getProduct(value).then((data) => {
						...
					});
				}),
			plugins: {
				sort: { disable: true }
			}
		})`

Cant get Value to be reactive. It show value from first table shown.

**Comment by benswanson-8451** [comment]
https://github.com/bryanmylee/svelte-headless-table/issues/93 addresses this issue and offers 2 workarounds.
