### ISSUE TITLE
Add missing `exports` condition

### ISSUE THREAD

**Issue by amr3k** [bryanmylee/svelte-headless-table#178]
Reference: https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition

**Comment by bfovez** [comment]
With more details:
`22:29:24 [vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

svelte-headless-table@0.17.7
svelte-render@1.6.1
svelte-subscribe@1.0.6

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.`

And all imports fail with SvelteKit 2:
`Could not find a declaration file for module 'svelte-headless-table'. 'c:/Users/xxxxx/node_modules/svelte-headless-table/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/svelte-headless-table` if it exists or add a new declaration (.d.ts) file containing `declare module 'svelte-headless-table';`ts(7016)`

**Comment by bryanmylee** [comment]
Closed by #176 and #181.
