### ISSUE TITLE
Cannot find module 'svelte-headless-table/plugins' or its corresponding type declarations on version 0.18.1

### ISSUE THREAD

**Issue by fromaline** [bryanmylee/svelte-headless-table#183]
Hi! Thanks for maintaining the project! I use it pretty extensively, and it's awesome.

However, I have the following issue in the new v0.18.1 release:

```ts
// Cannot find module 'svelte-headless-table/plugins' or its corresponding type declarations.ts(2307)
import { addSortBy, addTableFilter } from 'svelte-headless-table/plugins'
```

It seems like old imports don't work anymore. Is there a way to fix it?

**Comment by leonardsimonse** [comment]
Would seem to be related to https://github.com/bryanmylee/svelte-headless-table/issues/184
It seems like the IDE gets confused after the update. I've run `vite build` and it all of sudden started seeing the import again

**Comment by fromaline** [comment]
@leonardsimonse, thanks for your answer! Do you mean running `vite build` in the project directory? It doesn't seem to fix the issue in my case. Moreover, it's not just an IDE issue. When I manually run the TS check, I also get the same error.

**Comment by itsmepetrov** [comment]
the same issue, `vite build` and restarting of vscode do not help

**Comment by itsmepetrov** [comment]
temp fix:

```ts
// svelte-headless-table-plugins.d.ts

declare module "svelte-headless-table/plugins" {
  export * from "svelte-headless-table/dist/plugins"
}
```

do not forget to include this file in `tsconfig.json`

**Comment by AdrianGonz97** [comment]
@fromaline Please ensure that `"moduleResolution": "bundler"` is set in your `tsconfig.json` under `compilerOptions`. This tells typescript to check the `exports` map for the `types` condition in the dependency's `package.json`.
