### ISSUE TITLE
Sveltekit | "moduleResolution": "Bundler" | Cannot find module 'svelte-headless-table/dist/plugins' or its corresponding type declarations. 

### ISSUE THREAD

**Issue by bfovez** [bryanmylee/svelte-headless-table#184]
Hi,

This one is related to closed #173 .

I updated to 0.18.1.
I had to import from `svelte-headless-table/dist/plugins,` not from `svelte-headless-table/plugins`.
I don't know if it was what you meant.
And I had to import some stuff from `svelte-headless-table/dist/utils/...` too.

It `npm run check` well in `"moduleResolution": "node"` mode BUT, with `"moduleResolution": "bundler"`, the default mode set by `npm create svelte`, then `npm run check` spits out dozens of the following:

`Error: Cannot find module 'svelte-headless-table/dist/plugins' or its corresponding type declarations. `

**Comment by bryanmylee** [comment]
That's odd, I assumed that the `"node"` module resolution mode was compatible with everything.

Also, you should be able to import from `svelte-headless-table/plugins` due to the `"exports"` property on `package.json`.

Can I check which version of Svelte and SvelteKit you're on?

**Comment by bfovez** [comment]
Hi,

It is 10:50 PM here. I'll double-check tomorrow in the morning and let you know.

**Comment by bfovez** [comment]
Hi,
After double-check, I was wrong, my bad. It seems like vs code / ts compiler needs quite some time for taking in account the new version. After restarting vs code and forcing a new compilation, all is fine.
Thank you for the very useful headless table!
As for me, the issue can be closed
