### ISSUE TITLE
Property 'original' does not exist on type 'BodyRow<User, AnyPlugins>'.

### ISSUE THREAD

**Issue by isaacfink** [bryanmylee/svelte-headless-table#220]
I am trying to access two properties for the render, my specific use case is an avatar with a fallback to the username, I need to access two columns and I am doing it like this
```ts
table.column({
    accessor: 'avatar',
    header: 'Avatar',
    cell: ({ value, row }) => {
        console.log(row);
        return createRender(Avatar, { avatar: value, name: row.original.name });
    }
}),
```
And this works but I am getting a typescript error `Property 'original' does not exist on type 'BodyRow<User, AnyPlugins>'.`, is there a type safe way to achieve this?

**Comment by burguela** [comment]
Did you resolve this issue @isaacfink?

**Comment by isaacfink** [comment]
@burguela Yes, the solution is to use a function as an accessor instead of a key, this is how I did it for my example above

```ts
table.column({
    accessor:({name, avatar}) => ({name, avatar}),
    header: 'Avatar',
    cell: ({ value }) => {
        return createRender(Avatar, {...value});
    }
}),
```

**Comment by isaacfink** [comment]
If you do that you will probably want an explicit id as well if you plan on adding column ordering
