### ISSUE TITLE
Unable to have accessor be row number

### ISSUE THREAD

**Issue by olegpolin** [bryanmylee/svelte-headless-table#226]
How do I have the accessor for a column be the row number? Something like 
```
accessor: ( row ) => row.depth,
```
I am trying to add an actions menu, such as deleting a row based on row number, similar to https://www.shadcn-svelte.com/docs/components/data-table#row-actions

**Comment by olegpolin** [comment]
Oh it seems like `row.depth` is for sub-rows, using id might be better

**Comment by Destaq** [comment]
Did you figure out how to implement the delete functionality? Have some trouble with the reactivity.

**Comment by olegpolin** [comment]
> Did you figure out how to implement the delete functionality? Have some trouble with the reactivity.

You can use a writable in the `createTable` initializer, when the writable is updated, the table is updated.
