### ISSUE TITLE
feature request: add dataId to BodyRow type definition

### ISSUE THREAD

**Issue by mokshsinghji** [bryanmylee/svelte-headless-table#227]
Hi, I was using your excellent library, but I need to access the `row.dataId` in order to identify my rows for Sortable.js, and while this is available on the object itself, interestingly it is not on the type definition, giving me a TypeScript error. 

I can easily fix this or just ignore the error but I was wondering if it would be possible to add this to the type definition itself, so that it can be beneficial for others to discover and use if needed as well. 

I would probably try and look into this myself and make a PR, but creating an issue for tracking purposes.

**Comment by bryanmylee** [comment]
Hey, this is because a `row` could either be a [`DisplayBodyRow`](https://svelte-headless-table.bryanmylee.com/docs/api/body-row#displaybodyrow) or a `DataBodyRow`! Since `dataId` only exists on the `DataBodyRow`, you have to check the access with:

```svelte
<div id={row.isData() ? row.dataId : undefined} />
```
