### ISSUE TITLE
Is it possible to dynamically delete or at least update rows?

### ISSUE THREAD

**Issue by Destaq** [bryanmylee/svelte-headless-table#228]
Looked through the documentation and past issues but wasn't able to find any good examples concerning dynamically updating and/or deleting rows in the table. The most I discovered was the `on` listener but that does not seem to be able to catch custom dispatched events, making it not too useful for listening to updates.

Are there any ways with this library to easily re-render and delete content / rows without reloading?

**Comment by ArthurMynl** [comment]
```js
        const tableData = writable(data);
	$: tableData.set(data);

	const table = createTable(tableData, {
		page: addPagination(),
		sort: addSortBy(),
		filter: addTableFilter({
			fn: ({ filterValue, value }) => value.toLowerCase().includes(filterValue.toLowerCase())
		})
	});
```

Something like this should do the job :)

**Comment by bryanmylee** [comment]
The library is purely driven by the `$data` store that's passed in, so you should delete and update the elements in your data model to update the table. Given how I wrote the view model transformations, that won't re-render everything, at least not meaningfully!
