### ISSUE TITLE
[Question/Request] Integration with SvelteGantt

### ISSUE THREAD

**Issue by Primenotes** [bryanmylee/svelte-headless-table#24]
Awesome tool!
Trying to integrate it with the table module used in 'svelte-gantt' (https://github.com/ANovokmet/svelte-gantt/tree/master/src/modules/table). My point of struggle is that headless table doesn't seem to provide an object that reflects the 'displayed state' of the data in the table (sort -> with sorted items, grouping -> with switched children/parents). Any ideas how to derive that?

Example for sorting (e.g. item 0 in table is item 3 in object):
![grafik](https://user-images.githubusercontent.com/99910929/170698794-c6a62c0f-4aaf-4794-bfd2-bc5443c624e8.png)

**Comment by bryanmylee** [comment]
Am I right to assume that you're trying to associate a row item to the original item in the data?

I haven't had a chance to fully document the instance properties yet, but the default behaviour of Headless Table is to give each item a string id based on its index in the data array.

You then have two ways of referring to the original data item regardless of sorting / grouping:

1. The original id is stored on each row as `row.dataId`
2. A reference to the original data item is stored on each row as `row.original`

Let me know if this addresses your use-case! I'd be happy to extend the library to accomodate.

**Comment by bryanmylee** [comment]
Given the lack of updates, I'll assume that you've managed to solve the issue! I'll close this for now. If you have any remaining issues, do open this again.
