### ISSUE TITLE
Plugins break in dev mode on SvelteKit

### ISSUE THREAD

**Issue by Gildedter** [bryanmylee/svelte-headless-table#29]
Ok so, no matter what I try, `sortBy` just won't work, I copied the [simple example](https://svelte.dev/repl/cae6b8960e5a4c84a38826847aa862f3?version=3.48.0), but when I use the same example on my local machine, sorting just won't work, any ideas? I'm not getting any errors whatsoever, that's why I can't diagnose the issue

`package.json`:
```
"devDependencies": {
    "@babel/core": "^7.14.0",
    "@babel/preset-env": "^7.14.0",
    "@hurtigruten/svelte-table": "^2.0.3",
    "@iconify/svelte": "^2.2.1",
    "@sveltejs/adapter-static": "^1.0.0-next.26",
    "@sveltejs/kit": "next",
    "@testing-library/jest-dom": "^5.14.0",
    "@testing-library/svelte": "^3.0.0",
    "@types/jest": "^27.0.0",
    "@types/testing-library__jest-dom": "^5.14.0",
    "autoprefixer": "10.4.5",
    "babel-jest": "^27.0.0",
    "cross-env": "^7.0.3",
    "date-picker-svelte": "^2.0.0",
    "flowbite": "^1.4.5",
    "flowbite-svelte": "^0.17.3",
    "jest": "^27.0.0",
    "jspdf": "^2.5.1",
    "n2words": "^1.11.1",
    "postcss": "^8.4.12",
    "postcss-load-config": "^3.1.4",
    "svelte": "^3.44.0",
    "svelte-check": "^2.2.6",
    "svelte-headless-table": "^0.10.2",
    "svelte-jester": "^2.0.1",
    "svelte-preprocess": "^4.9.4",
    "svelte-typeahead": "^4.2.2",
    "tailwindcss": "^3.0.23",
    "ts-jest": "^27.0.0",
    "tslib": "^2.3.1",
    "typescript": "^4.6.2",
    "wretch": "^1.7.9",
    "xlsx": "https://cdn.sheetjs.com/xlsx-0.18.9/xlsx-0.18.9.tgz"
  },
  ```
  `svelte.config.js`
```
/** @type {import('@sveltejs/kit').Config} */
const config = {
    // Consult https://github.com/sveltejs/svelte-preprocess
    // for more information about preprocessors
    preprocess: preprocess({ postcss: true }),

    kit: {
        adapter: adapter(),

        // Apply the proxy setup
        vite: () => ({
            server,
            optimizeDeps: {
                include: ['fuzzy'],
            },
        }),
    },
};

export default config;
```

_Originally posted by @Gildedter in https://github.com/bryanmylee/svelte-headless-table/issues/28#issuecomment-1162556068_

**Comment by Gildedter** [comment]
Even though `addPagination` works, `addSortBy` doesn't, I have referred to the kitchen sink example

**Comment by Gildedter** [comment]
I think I found the issue, `order` is undefined because both of my `cell.props()`, are empty objects `{}`, I checked by using `JSON.stringify(cell.props())`
  ```
  <table {...$tableAttrs}>
  <thead>
    {#each $headerRows as headerRow (headerRow.id)}
      <!-- <Subscribe rowAttrs={headerRow.attrs()} let:rowAttrs> -->
      <Subscribe
        rowProps={headerRow.props()}
        let:rowProps
        rowAttrs={headerRow.attrs()}
        let:rowAttrs
      >
        <tr {...rowAttrs}>
          {#each headerRow.cells as cell (cell.id)}
            <Subscribe
              attrs={cell.attrs()}
              let:attrs
              props={cell.props()}
              let:props
            >
              {JSON.stringify(cell.props())}
              <th {...attrs} on:click={props.sort.toggle}>
                <Render of={cell.render()} />
                {#if props.sort.order === "asc"}
                  ⬇️
                {:else if props.sort.order === "desc"}
                  ⬆️
                {/if}
              </th>
            </Subscribe>
          {/each}
        </tr>
      </Subscribe>
    {/each}
  </thead>
  <tbody {...$tableBodyAttrs}>
    {JSON.stringify($tableBodyAttrs)}
    {#each $rows as row (row.id)}
      <Subscribe rowAttrs={row.attrs()} let:rowAttrs>
        <tr {...rowAttrs}>
          {#each row.cells as cell (cell.id)}
            <Subscribe attrs={cell.attrs()} let:attrs props={cell.props()}>
              {JSON.stringify(cell.props())}
              <td {...attrs}>
                <Render of={cell.render()} />
              </td>
            </Subscribe>
          {/each}
        </tr>
      </Subscribe>
    {/each}
  </tbody>
</table>
  ```

**Comment by Gildedter** [comment]
When I do:
```
  <Subscribe
    attrs={row.attrs()}
    let:attrs
    props={row.props()}
    let:props
  >
```
my Intellisense on props gives me: `{ sort: never }`

**Comment by eric-naguras** [comment]
Following. I have the same issue. Trying in a new, default Sveltekit project.
Also, the Simple Table Filtering (https://svelte.dev/repl/b14e9a90ad6c40ab85b18c9421820487?version=3.48.0) shows the table body for about half a second and then disappears. No idea why. No errors or anything.
I would love to see this table component work with Sveltekit.

**Comment by bryanmylee** [comment]
@Gildedter @eric-naguras Can you try the example again with `npm run build && npm run preview`?

I suspect there's an issue with `npm run dev` that's causing Svelte Headless Table to trip up.

**Comment by eric-naguras** [comment]
@bryanmylee Thanks for your swift reply.
Running build and preview did the trick for the table filtering.
I'll check if this is also true for the column sorting.

Any idea if this is fixable or should I just hope it will go away with an update of Sveltekit?
I'm on v1.0.0-next.350 right now. with @sveltejs/adapter-cloudflare on 1.0.0-next.23.

When things work using build and preview that is okay for me.
Would be nice when things work in dev but now a deal breaker for me.
It's hard enough to find a working data table.

**Comment by bryanmylee** [comment]
@eric-naguras It's likely an issue with how Svelte Headless Table interacts with SvelteKit, as the REPL and production works fine. I'll look into the issue and update you when I figure it out!

**Comment by eric-naguras** [comment]
@bryanmylee The sorting example is working too when used with build/preview.
But it does not work running dev.
Cool, I'll try some more examples and will probably using this in my apps.
The TanStack table for Svelte is missing a lot of functionality. I like this one much more.

**Comment by eric-naguras** [comment]
> @eric-naguras It's likely an issue with how Svelte Headless Table interacts with SvelteKit, as the REPL and production works fine. I'll look into the issue and update you when I figure it out!

Take your time, build-preview works for me right now.

Thanks.

**Comment by bryanmylee** [comment]
@eric-naguras @Gildedter Can I check if you are both using `pnpm`?

From my testing, the library works fine with SvelteKit in dev mode when installed with `npm`.

If you're using `pnpm`, then the SSR works fine but the client render / hydration fails. That explains why you see a flash of correct content before the table content disappears.

I'm absolutely stumped as to why this is, but if you need dev mode consider using `npm`.

**Comment by eric-naguras** [comment]
@bryanmylee I'm not using pnpm but regular npm., v 8.12.1

**Comment by PoisnFang** [comment]
> @bryanmylee I'm not using pnpm but regular npm., v 8.12.1

Same, its NOT just pnpm

**Comment by bryanmylee** [comment]
> > @bryanmylee I'm not using pnpm but regular npm., v 8.12.1
> 
> Same, its NOT just pnpm, please update the title of the issue @bryanmylee Can you share the repo you used for testing?

I'm using this repository's `src/routes/index.svelte` and the documentation repo on `docs/src/routes/index.svelte`. I haven't tried on a fresh install of SvelteKit yet though.

**Comment by bryanmylee** [comment]
I'm having a hard time debugging this, and I suspect it's an issue with the package manager's interactions with SvelteKit.

If I try to use `npm link` to debug the package, the issue goes away. I've tried debugging the issue by adding `console.log` to the `node_modules` version but I can't find anything.

If anyone else has ideas on what this might be I'd appreciate the help and contribution.

**Comment by MellenIO** [comment]
For what it's worth, I'm encountering the same issue with npm `7.21.1` and node `16.9.1`. Running `npm link` doesn't seem to fix this for me, however.

**Comment by MellenIO** [comment]
It looks like there might be some issues with creating `cell` as `DataHeaderCell`. If I comment out this line:
https://github.com/bryanmylee/svelte-headless-table/blob/main/src/lib/plugins/addSortBy.ts#L198

then I can at least get the `toggle` function to execute, which will update `props.sort.order` - but doesn't seem to do anything else.

Looks like something in SvelteKit dev mode is causing `FlatHeaderCell` to not exist as a class? I could be looking at this wrong - but this seems to at least be the case when comparing `npm run dev` (left) compared to a built version (right) of the app.
![firefox_nHKFA4w5p4](https://user-images.githubusercontent.com/1464589/180772045-8c7ceff0-fbd7-4f0b-9759-99fbc4d86748.png)

**Comment by bryanmylee** [comment]
@MellenIO Thanks for the insight! That's really interesting and might explain the issue. I'll look into any issues with Vite and class generation.

**Comment by rohanrajpal** [comment]
> I'm having a hard time debugging this, and I suspect it's an issue with the package manager's interactions with SvelteKit.
> 
> If I try to use `npm link` to debug the package, the issue goes away. I've tried debugging the issue by adding `console.log` to the `node_modules` version but I can't find anything.
> 
> If anyone else has ideas on what this might be I'd appreciate the help and contribution.

Thanks for this, the following workaround fixes the issue for me:

1. Clone this repo
2. run `npm i && npm run package`
3. Go to my Sveltekit project and run `pnpm link <path-to-package-dir`

Tho ofcourse its a temporary fix, but yes it looks like a class generation issue for sure.

**Comment by bryanmylee** [comment]
@JBevvy Unfortunately not. . Unfortunately, my free time is quite limited so I haven't reached out to Vite yet but I highly suspect it's a class generation issue.

**Comment by bryanmylee** [comment]
> It looks like there might be some issues with creating `cell` as `DataHeaderCell`. If I comment out this line: https://github.com/bryanmylee/svelte-headless-table/blob/main/src/lib/plugins/addSortBy.ts#L198
> 
> then I can at least get the `toggle` function to execute, which will update `props.sort.order` - but doesn't seem to do anything else.
> 
> Looks like something in SvelteKit dev mode is causing `FlatHeaderCell` to not exist as a class? I could be looking at this wrong - but this seems to at least be the case when comparing `npm run dev` (left) compared to a built version (right) of the app. ![firefox_nHKFA4w5p4](https://user-images.githubusercontent.com/1464589/180772045-8c7ceff0-fbd7-4f0b-9759-99fbc4d86748.png)

@MellenIO Would it be possible to create a reproduction of the issue on a smaller repo? Seems like you've gotten the furthest with debugging this issue and I'd like to understand this better before submitting an issue to VIte.

**Comment by bryanmylee** [comment]
<img width="1074" alt="Screenshot 2022-08-04 at 1 53 32 PM" src="https://user-images.githubusercontent.com/42545742/182773078-15d5f096-f63a-4135-8804-0235149e1eb0.png">

Seems to be an issue with the `instanceof` check. The cell is logged as a `DataHeaderCell` but the `instanceof` check is failing.

**Comment by bryanmylee** [comment]
> No errors thrown, table is rendering and using the columnsFilter Repl as a boiler plate. intellisense reult is the same as reported previously: `let props: { filter: never; }`

Can I check where you're getting `props: { filter: never }`? Usually if the plugin shows `never`, it's because you're accessing the props of the wrong table component e.g. accessing header row props in a body row.

**Comment by bryanmylee** [comment]
I've developed a workaround for the `instanceof` checks to get around the Vite dev issue.

Please install `v0.13.0` and let me know if you still run into this issue @Gildedter  @MellenIO @eric-naguras @rohanrajpal @JBevvy.

Thanks everyone for your continual support and effort in debugging this issue. I hope this solves the biggest pain point with the library.

**Comment by rohanrajpal** [comment]
@bryanmylee Just installed and things seem to be working as expected! Really appreciate all your efforts in making this library better every week.

I'll try to find some time in the coming weeks to fix this issue, tho seems like it's a tricky one to understand.

**Comment by bryanmylee** [comment]
Given the improved ergonomics of the workaround, I'm going to consider this problem solved for now.

**Comment by CWAscend** [comment]
I had a similar issue, Vue3. The issue was this in one of my props:

![image](https://github.com/bryanmylee/svelte-headless-table/assets/134165900/ce02ece1-f7ef-4af6-a9fb-5338c7160668)
