### ISSUE TITLE
Conditional row styling how?

### ISSUE THREAD

**Issue by Gildedter** [bryanmylee/svelte-headless-table#30]
So I'm preprocessing my data, and adding in a `invalid: (predicate result)` key on my object, I'd like to style the "invalid" rows to have a red background color, I tried:
```
<Subscribe
  attrs={row.attrs()}
  let:attrs
  props={row.props()}
  let:props
>
  <tr
    {...attrs}
    class="bg-white border-b dark:bg-gray-800 dark:border-gray-700"
    class:invalid={props.} // intellisense won't show my my original object here
  >
```
but `props` won't let me access the "invalid" key, same with `attrs`

**Comment by bryanmylee** [comment]
I need to update the documentation to better describe the `BodyRow` object.

You can use `row.original` to refer to the original data item for that row. You can then do:

```svelte
<Subscribe
  attrs={row.attrs()}
  let:attrs
  props={row.props()}
  let:props
>
  <tr
    {...attrs}
    class="bg-white border-b dark:bg-gray-800 dark:border-gray-700"
    class:invalid={row.original.invalid}
  >
```

**Comment by Gildedter** [comment]
Works perfectly, only the typings are missing, so there's an error on the editor at the moment
