### ISSUE TITLE
How to nest a table inside expanded row?

### ISSUE THREAD

**Issue by Gildedter** [bryanmylee/svelte-headless-table#31]
from the [example](https://svelte-headless-table.bryanmylee.com/docs/plugins/add-expanded-rows#simple-row-expanding), I see that it just hides the same dataset, but what if I want to load an entirely different object array

**Comment by bryanmylee** [comment]
Svelte Headless Table works off having one source of data for the entire table. If you want to load a different object array when expanding a row, you can listen for a click on the expanding element to fetch the data you want, then update the original data store to add the fetched data as a property on the clicked item.

You can then use `addSubRows` to tell Svelte Headless Table to treat that property as a subrow for each row.

```svelte
<script>
  const data = writable([...]) // where each element has `id` and an optional `nested` field.
  
  const table = createTable(data, {
    nested: addSubRows({ children: 'nested' }),
    expand: addExpandedRows(),
  });

  const fetchData = async (rowId) => {
    const nestedData = await fetch(..); // get your data here.
    const idx = $data.findIndex(item => item.id === rowId);
    $data[idx].nested = nestedData;
    $data = $data;
  };
  ...
</script>
...
{#each $rows as row (row.id)}
  <Subscribe rowAttrs={row.attrs()} let:rowAttrs>
    <tr {...rowAttrs} on:click={() => fetchData(row.id)}>
      {#each row.cells as cell (cell.id)}
        <Subscribe attrs={cell.attrs()} let:attrs>
          <td {...attrs}>
            <Render of={cell.render()} />
          </td>
        </Subscribe>
      {/each}
    </tr>
  </Subscribe>
{/each}
```

**Comment by Gildedter** [comment]
I'll try this thanks

**Comment by Gildedter** [comment]
Didn't work as I'd hope, I pre-process my data, and it has a key that already holds an array of objects as opposed to `nestedData` that's retrieved from somewhere, as a work around I'm making a button modal via `table.display( { cell: modalButton} )`, where I pass the array of objects to the modal for viewing, dunno how to retrieve it from `rows` though

**Comment by Gildedter** [comment]
What I ended up with:
```
  const columns = table.createColumns([
    table.display({
      id: "show",
      header: "",
      cell: ({ row }) => {
        const { collection, key} = row.original; // no typings for original on index.d.ts
        return createRender(ButtonWithModal, {
          source: [...collection],
          id: key,
        });
      },
    }),
```

**Comment by bryanmylee** [comment]
@Gildedter I'll look into fixing the typings for the row property passed in

**Comment by bryanmylee** [comment]
@Gildedter The reason why `row.original` is not typed there is because not all rows will have an `original` property.

One common example: if the row is a display row created by grouping other rows together, nothing with static typing really fits into `original`. Therefore your code above will fail if you use row grouping and aggregation.

This is a documentation mistake on my part. I'll export all the internal classes used for these checks so you should be able to do:

```ts
const columns = table.createColumns([
  table.display({
    id: "show",
    header: "",
    cell: ({ row }) => {
      if (!(row instanceof DataBodyRow)) {
        return "";
      }
      const { collection, key} = row.original; // no typings for original on index.d.ts
      return createRender(ButtonWithModal, {
        source: [...collection],
        id: key,
      });
    },
  }),
  ...
]);
```

**Comment by fromaline** [comment]
@bryanmylee, hi! First of all, thanks for the library!

I applied your fix, but types are still missing. `row.original` is just `DataBodyRow<any, any>.original: any`.
