### ISSUE TITLE
renderJSON fn for Table

### ISSUE THREAD

**Issue by larryhengl** [bryanmylee/svelte-headless-table#32]
Hi, this library is awesome, thanks for putting it together and sharing it!

Is there a shortcut approach to "exporting" the current Table state as a JSON collection?  With all sorting and filters applied, and col state (hidden), derived cols, and col names as keys, etc?

If not, then any advice on how best to hit the API to construct a custom renderJSON() for the Table?  Or just brute force it?  ;-)

Scientific apps I build tend to require dumping table state as csv files, which I typically do from JSON collections created from stores and applied app state.

Many thanks!

-Larry

**Comment by bryanmylee** [comment]
I've never considered that, but it's definitely doable with the current API right now.

We could create a derived store on the table view model that describes the data as a JSON structure. You can then either subscribe to the store for live updates to the JSON tree or use [`get`](https://svelte.dev/docs#run-time-svelte-store-get) to get the value once.

**Comment by bryanmylee** [comment]
Perhaps a more extensible way is to write a plugin for this actually.

Since each plugin has access to the table state, it can export some plugin state that describes the current view model.

I'll look into releasing this for v0.11.

**Comment by bryanmylee** [comment]
@larryhengl I've released v0.11.0 which should address your needs.

**Comment by larryhengl** [comment]
thanks @bryanmylee , that's so awesome that you added that export feature so quickly.  much appreciated!!
