### ISSUE TITLE
Add example to conditionally add styling to rows, columns & cells

### ISSUE THREAD

**Issue by adammmiller** [bryanmylee/svelte-headless-table#36]
Really enjoying working with svelte-headless-table so far! It would be great if we could add an example on how to conditionally apply styles to individual rows/columns/cells. E.g. append a style to the first column and all rows under `<tbody>`

From the example I can see this gets applied by:
```
      <Subscribe rowAttrs={row.attrs()} let:rowAttrs>
        <tr {...rowAttrs}>
```

Can we include an example of how you'd pass values into `rowAttrs` from `table.createColumns`?
Thanks

**Comment by bryanmylee** [comment]
`attrs()` is supposed to be purely for DOM attributes, and `props()` is for any additional properties provided by plugins. I'm sorry if that wasn't clear and I'll try to improve the documentation explaining it.

As for conditional styles, it depends on how the condition is derived! Most likely, your conditional styles will depend on your data.

# Conditional styles on rows

If the styles depend on the data item itself, I would either add properties to each item of `$data` and extend its type definition. Then, you can reference the data item with [`row.original`](https://svelte-headless-table.bryanmylee.com/docs/api/body-row#original-item).

```svelte
<tr
  class:special={row instanceof DataBodyRow && row.original.special}
>
  ...
</tr>
```

You could also derive the condition inline.

```svelte
<tr
  class:special={
    row instanceof DataBodyRow
    && row.original.firstName.startsWith('A')}
>
  ...
</tr>
```

# Conditional styles on columns

If you want to apply a conditional style on column elements, you can either pass a custom [`cell`](https://svelte-headless-table.bryanmylee.com/docs/api/create-columns#columndef-cell-column-row-value-state-renderconfig) to render when creating your columns, or check [`cell.id`](https://svelte-headless-table.bryanmylee.com/docs/api/body-cell#id-string) in the markup.

```svelte
<tr>
  {#each row.cells as cell (cell.id)}
    <Subscribe attrs={cell.attrs()} let:attrs>
      <td {...attrs} class:special={cell.id === 'firstName'}>
        <Render of={cell.render()} />
      </td>
    </Subscribe>
  {/each}
</tr>
```

**Comment by bryanmylee** [comment]
I'm going to mark this as closed if you have no further questions.
