### ISSUE TITLE
Add a "select all" option for `addSelectedRows` plugin

### ISSUE THREAD

**Issue by MellenIO** [bryanmylee/svelte-headless-table#37]
This is probably my favourite Svelte libraries, it's so useful and versatile! Thank you so much for making this.

I do have one small gripe, which is that there isn't a "select all" option for the `addSelectedRows` plugin. This can be hacked in like so:

```
// on init
let tableColumns = [];
    let selectAll = writable(false);
    if (selectable) {
        tableColumns.push(table.display({
			id: 'selected',
			header: () => createRender(Checkbox, { // renders the "select all"
                isSelected: selectAll
			}),
			cell: ({ row }, { pluginStates }) => {
                const { isSelected } = pluginStates.select.getRowState(row);
                return createRender(Checkbox, {
                    isSelected
				});
			},
			plugins: {
                sort: {
                    disable: true
				}
			}
		}));
	}
// ... continue initialising columns
```

and then subscribing to the newly created `selectAll` to cascade the changes to all other checkboxes:
```
const { selectedDataIds } = pluginStates.select;

    if (selectable) {
        selectAll.subscribe(val => {
            if (!val) selectedDataIds.clear();
            else {
                let rows = $pageRows;
                let newSelected = {};
                for (const row of rows) {
                    newSelected[row.id] = true;
                }

                $selectedDataIds = { ...newSelected };
            }
        });
	}
```

This works fine, but could run in to issues when trying to do things the other way around - ie. trying to select the "select all" option when all rows are selected. You could probably do something like:
```
selectedDataIds.subscribe(val => {
    if (val.length !== $pageRows.length) return;

    let newValue = true;
    for (const rowVal of val) {
        if (!rowVal) {
            newValue = false;
            break; // exit early
        }
    }

    $selectAll = newValue;
});
```
But you may run in to issues w/ constantly cascading changes between the 2 `subscribe` functions.

It'd be nice if there was a sane default for a select all option, especially if it were performant - I'm not _too_ worried about the performance of the library, but for my use case actually these headless tables take up the bulk of the application so I do get slightly wary about having to implement some of these things.

Thanks again for the library, however, it's saved me countless hours over the last month (and will continue to do so)!

**Comment by bryanmylee** [comment]
Sure thing, I'l look into providing a `selectAll` method on the data IDs store that's bound to the internal row state.

**Comment by bryanmylee** [comment]
@MellenIO Can I check with you that you want a `selectAll` and `deselectAll` method on the ID store?

**Comment by MellenIO** [comment]
@bryanmylee that would be nice, but I think really the easiest way would actually just be to have an `allSelected` boolean so you could toggle it that way (since `selectAll` and `deselectAll` would just end up being aliases for `allSelected = true/false` respectively)

The biggest thing is being able to automagically detect if all are selected so that I can update the "select all" header. As it stands, my tables won't update that header even if all are selected due to cascading subscribes (and performance concerns). So you could actually select all rows manually but it wouldn't properly show that in the header.

![image](https://user-images.githubusercontent.com/1464589/183465862-74f678c8-2654-48dd-8392-cdb35ec689c8.png)

**Comment by bryanmylee** [comment]
@MellenIO Ah I get what you need now. I'll build the feature out accordingly.

**Comment by bryanmylee** [comment]
@MellenIO I've added this to the plugin in v0.13.3.

You can find its documentation [here](https://svelte-headless-table.bryanmylee.com/docs/plugins/add-selected-rows#allrowsselected-writable-boolean).
