### ISSUE TITLE
Add a "high level filter" plugin

### ISSUE THREAD

**Issue by MellenIO** [bryanmylee/svelte-headless-table#40]
One of the things this library is missing (but could probably add reasonably easily - he says...) is the ability to add what I will call "high level" table filters.

In short, these would be moreso "descriptive" filters that don't align with a specific column or existing filter. As an example, a high level filter may be:
```
name: High Value
filter: row => row.value > 700 && row.status !== 'refunded'
```

The idea is that you could apply many high level filters, acting as either an AND or an OR. These could be toggled at any time dynamically changing the available rows for export, viewing etc.

**API examples**
```
// sidenote: could either have an extra "name" field, or use "key" as the "name" AND the key
createTable(data, {
    highLevelFilters: addHighLevelFilters({
        method: 'AND', //AND, OR
        filters: [
            {
                key: 'high-value',
                fn: row => row.value > 700 && row.status !== 'refunded'
            },
            {
                key: 'low-value',
                fn: row => row.value < 700 && row.status !== 'refunded'
            },
            {
                 key: 'recent',
                 fn: row => row.date >= new Date((new Date().getDate()) - 7) //not _technically_ correct but just as an example
            }
    ])
});

// ... getting filters
const { appliedFilters, filterMethod, availableFilters } = pluginStates.highLevelFilters;

// ... toggle filter
appliedFilters.toggle('high-value');

// ... add filter
appliedFilters.add('high-value');

// ... remove filter
appliedFilters.remove('high-value');

// ... set filter method
$filterMethod = 'OR';

// ... render available filters
{#each $availableFilters as filter }
    <button on:click={() => appliedFilters.toggle(filter.key)}>toggle {filter.key}</button>
{/each}
```

Not sure how you would feel about something like this, but at least for my use case it'd be super helpful.

I can probably contribute this myself but I'm really not that great with TypeScript so might need someone to jump in and type-ify it for me.

**Comment by bryanmylee** [comment]
Correct me if I'm wrong, but you're looking for a filtering mechanism that can perform complex nested filters based on the data available?

Svelte Headless Table provides a [`addTableFilter`](https://svelte-headless-table.bryanmylee.com/docs/plugins/add-table-filter) which lets you do a text search on the entire table.

The main justification is that the text data presented on the table is not always representative of the data model backing the table, so we needed a way to filter the table after it's rendered.

But in your case, it seems like you want to filter the `$data` store itself based on its values before it's rendered to the table. In that case, would it be possible to derive a `$filteredData` store based on your needs?

```ts
const data = writable(...);
const filters = writable(...);
const filteredData = derived([data, filters], ([_data, _filters])  => {
  return applyFilters(_data, _filters);
});
const table = createTable(filteredData);
...
```

**Comment by bryanmylee** [comment]
This use case seems to be best handled with a filter on `data` itself. Please feel free to re-open if there are any further issues.
