### ISSUE TITLE
createRender and event dispatcher

### ISSUE THREAD

**Issue by flavio-greenfact** [bryanmylee/svelte-headless-table#45]
Not sure how to read an event while using createRender. I have a dropdown menu which I could render like below

    <UserActionsDropdown on:message={handleMessage}/> 

I want to dispatch an event from UserActionsDropdown and be able to handle in the table below. How would be possible?

    table.column({
		header: '',
		id: 'selected',
		accessor: (item) => item,
		cell: ({ value }) => {
			return createRender(UserActionsDropdown, {
				userId: value.id
			});
		}
	})

**Comment by bryanmylee** [comment]
Unfortunately, Svelte's event handling is internal behaviour. There are some tricks I could do to expose event listeners but it would be near impossible to get type safety and would further complicate the API.

My advice is to pass a callback function as a prop of the component and attach it to the event handler.

```ts
// App.svelte
function handleMessage(message: Message) {...}

table.column({
  header: '',
  id: 'selected',
  accessor: (item) => item,
  cell: ({value}) => createRender(UserActionsDropdown, {
    userId: value.id,
    onMessage: handleMessage,
  })
});
```

```svelte
<!-- UserActionsDropdown -->
<script lang="ts">
  export let userId: string;
  export let onMessage: (message: Message) => void;
  ...
</script>

<div on:click={() => handleMessage(...)}/>
```

**Comment by rohanrajpal** [comment]
> Unfortunately, Svelte's event handling is internal behaviour. There are some tricks I could do to expose event listeners but it would be near impossible to get type safety and would further complicate the API.
> 
> My advice is to pass a callback function as a prop of the component and attach it to the event handler.
> 
> ```ts
> // App.svelte
> function handleMessage(message: Message) {...}
> 
> table.column({
>   header: '',
>   id: 'selected',
>   accessor: (item) => item,
>   cell: ({value}) => createRender(UserActionsDropdown, {
>     userId: value.id,
>     onMessage: handleMessage,
>   })
> });
> ```
> 
> ```svelte
> 
> <script lang="ts">
>   export let userId: string;
>   export let onMessage: (message: Message) => void;
>   ...
> </script>
> 
> <div on:click={() => handleMessage(...)}/>
> ```

Actions indeed are not that extendible yet :(
Tho I would strongly recommend that this example can be added to the docs. I'm sure a lot of people would have this doubt. Thanks for this great example btw! Solved my use case.

**Comment by bryanmylee** [comment]
@rohanrajpal Refer to #54 and the [updated documentation](https://svelte-headless-table.bryanmylee.com/docs/api/create-render#on-type-eventtype-handler-ev-void) for `v0.15.0` for a new event system on the render system.
