### ISSUE TITLE
Plugin 'addDataExport': Value of Properties expanded and selected is always 'null'

### ISSUE THREAD

**Issue by BlueFoxPrime** [bryanmylee/svelte-headless-table#46]
Awesome work, currently exploring the possibilities!

Noticed the following issue:
Properties expanded and selected of $exportedData remain 'null' although rows are expanded/ selected.
![grafik](https://user-images.githubusercontent.com/112826784/188331631-0d691043-1aa1-491b-b4f0-0a75f029e408.png)

Example REPL:
https://svelte.dev/repl/6252bf57d8c64a59bd347e311241ebf2?version=3.48.0

I am still quite new to svelte so maybe the error is on my side. I'd be greatful for a hint in that case.

**Comment by bryanmylee** [comment]
Thanks for the report. This seems to be a bug with how the plugins interface with each other. I'll look into a fix.

**Comment by bryanmylee** [comment]
The issue with the expanded and selected columns is that they are display columns which do not contain any data. Therefore, when the `addDataExport` plugin receives rows, it does not see any data on those columns.

Generally, I'd advise you to use the `pluginStates.select.selectedDataIds` and `pluginStates.expand.expandedIds` stores, but I'll spend some more time thinking about how the `addDataExport` plugin should work.

**Comment by bryanmylee** [comment]
@BlueFoxPrime You can refer to the [updated documentation](https://svelte-headless-table.bryanmylee.com/docs/plugins/add-data-export) on the `addDataExport` plugin for the context discussed here and upgrade to `v0.13.4` for a first-class solution.
