### ISSUE TITLE
Allow multiple group-on features for columns

### ISSUE THREAD

**Issue by BlueFoxPrime** [bryanmylee/svelte-headless-table#51]
Hi,

I'd like to request the following feature(s):

- Possibility for several grouping options per column
- Possibility for grouping base on child layer props (e.g. item.children.age instead of item.age / 'value'), All parents of grouped layers should be ignored in that case.

Illustrating Picture (edited):
![image](https://user-images.githubusercontent.com/112826784/190130340-5919e07a-5e0a-409b-b103-753fddd0ced9.png)

Illustrating REPL (Basis for the picture):
https://svelte.dev/repl/320d8a80589a4c34950e335ae377f60f?version=3.50.1

Reason:
I want the table to describe the 'natural structure of a product' (consisting of different parts as children or even grand children).  
However I want to be 'able to change the score' quickly to only look at child layers (e.g. part level). 

I hope you can understand what I mean (:

**Comment by BlueFoxPrime** [comment]
Thanks for your ideas regarding multiple grouping options. I didn't think of defining two addGroupBy plugins. It sounds fine to me!

> It seems like you want to flatten the data by removing all parents and making the child elements the first layer, then group those rows together.

Thats exactly what I want 👍 

> I can look into writing a flattening plugin which you can then enable before grouping, something like:

> <button on:click={() => {
  props.flatten.toggle();
  props.group.toggle();
}}>Group children</button>

 Sounds good! It would be nice if you could include an option for which level of the elements to flatten on.

Your effort is much appreciated!

**Comment by bryanmylee** [comment]
@BlueFoxPrime Flattening of rows is now available with the [`addFlatten` plugin](https://svelte-headless-table.bryanmylee.com/docs/plugins/add-flatten).
