### ISSUE TITLE
Plugin 'addGroupBy' + 'addExpandedRows' - Missing Children / Expand option if grouped by column - Issue

### ISSUE THREAD

**Issue by BlueFoxPrime** [bryanmylee/svelte-headless-table#52]
Hi,

I noticed the following issue when combining the two mentioned plugins on nested data:
- Children / Expand option is missing for rows that are grouped by column, although items originally have children when not grouped 

Example picture:
![image](https://user-images.githubusercontent.com/112826784/190232985-bcc43d92-e8f2-4081-8e80-03497e6eadd6.png)

Example REPL:
https://svelte.dev/repl/320d8a80589a4c34950e335ae377f60f?version=3.50.1

In case that I overlooked something please give me a hint, thank you! (:

**Comment by bryanmylee** [comment]
This is definitely a bug in how the `addGroupBy` plugin resolves child rows. I'll look into a fix!

**Comment by bryanmylee** [comment]
This should be fixed in `v0.14.2`.
