### ISSUE TITLE
Table event system or plugin

### ISSUE THREAD

**Issue by FluffyDiscord** [bryanmylee/svelte-headless-table#54]
Right now it's painful to work with cell events.

I have a situation, where my table row last column is an "action" column with bunch of buttons (eg. edit, delete) and I would like to listen to the dispatched event from the cell right at the table component or even outside of it to process it and modify the table data.

The `Render` component now blocks custom events and using solution in https://github.com/bryanmylee/svelte-headless-table/issues/45 seems kind of dirty.

I need to dynamically listen to my unknown list of actions (row A can have one action, row B three and row C won't have any)

I think some simple table event system would be great - dispatch event which would automaticaly include the current cell and my custom data.

Example at my custom cell
```html
 <script>
    export let dispatchTableEvent // provided by this library, equivalent of `createEventDispatcher()` output
    
    const handleMyEvent = () => {
      dispatchTableEvent("my_event", {
        my_custom_payload: "world",
      })
    }
</script>


<button on:click|preventDefault={handleMyEvent}>
  HELLO
</button>
```

Example at table definition
```js
const { events } = table.createViewModel(columns)

// or events.on()
events.addListener("my_event", (e) =>{
  e.detail.cell // dispatched DataCell object
  e.detail.my_custom_payload // any other payload I defined
})

// or make it universal
events.any((e) =>{
  // handle any dynamic event type
})
```

I am aware that I can make this system myself as a separate thing or perhaps as a plugin (I am not sure how would I go around adding custom props to each cell - the event dispatcher), but it would be nice to have it build in.

Would that be considered as a "bloat" that user can do himself and you would rarther have cleaner/simpler package ?

**Comment by bryanmylee** [comment]
hey @FluffyDiscord, thanks for bringing the feature request and ideas!

I've been dabbling with Svelte's internal event system a little bit more, and it might be possible to dispatch events out of the `<Render />` component, but I'll have to get back to you on that later, especially if I want to preserve type safety.
