### ISSUE TITLE
Setup issues with pnpm(?)

### ISSUE THREAD

**Issue by kuechlerm** [bryanmylee/svelte-headless-table#60]
I had some issues using the headless-table in a current SvelteKit project using PNPM.

I got it running after installing 
- svelte-render
- svelte-subscribe

But there was no error that pointed to that solution.

Additionally I have a problem with typings. Importing the package in a svelte component with the lang="ts" attribute says 
`Could not find a declaration file for module 'svelte-headless-table'`

Any ideas how to fix that? Thank you!

**Comment by bryanmylee** [comment]
This might be related to my migration to Svelte package. I'll release a patch version to resolve this.

**Comment by bryanmylee** [comment]
The typing issue should be fixed with `v0.15.1`.

**Comment by kuechlerm** [comment]
That does the trick. Thank you!

**Comment by gwendalF** [comment]
Hello, I have the same issue with typings using npm. I have the version 0.17.5
I don't use sveltekit but only svelte maybe it's related? Because I see the typings in the lib folder but it don't seem to be parts of the exports mapping.
