### ISSUE TITLE
setting allPageRowsSelected to "false" clears entire selection, not just the current page

### ISSUE THREAD

**Issue by blerrgh** [bryanmylee/svelte-headless-table#80]
Writing `true` to the `allPageRowsSelected` store adds _only_ the current page's IDs to the `selectedDataIds` store, as expected.

But setting it to `false` clears _all_ selected rows, not only the ones on the current page.

I would expect the behavior to be consistent where setting true and false add/remove current page IDs only.

Relevant code in [addSelectedRows.ts](https://github.com/bryanmylee/svelte-headless-table/blob/main/src/lib/plugins/addSelectedRows.ts)
```
		const setAllPageRowsSelected = ($allPageRowsSelected: boolean) => {
			if ($allPageRowsSelected) {
				const $pageRows = get(tableState.pageRows);
				const pageDataIds = $pageRows
					.map((row) => (row.isData() ? row.dataId : null))
					.filter(nonNull);
				selectedDataIds.addAll(pageDataIds);
			} else {
				selectedDataIds.clear();
			}
		};
```

**Comment by bryanmylee** [comment]
Hi @blerrgh, thanks for your continual contributions and bug reports. This project has rapidly grown in complexity as I've continued to add features, and these reports really help me refine the library.

This bug has been resolved with #81.
