### ISSUE TITLE
`useExpanded` plugin

### ISSUE THREAD

**Issue by bryanmylee** [bryanmylee/svelte-headless-table#9]
Allow data items to specify sub-items and render them as subrows.

The column model will also need to be extended to allow for `DisplayColumn`s that do not represent any data property, but represents additional UI for row expansion state etc.

**Comment by bryanmylee** [comment]
Certain plugins result in incompatible behaviours when used with `useExpanded`. More specifically, the biggest issue comes from the `useSortBy` plugin, as its behaviour is not clear when used with `useExpanded`.

Currently, `useExpanded` only evaluates the rows of a nested group of items if the parent item is expanded i.e. it lazily computes the rows required to display subRows. This prevents a sorting plugin from pre-sorting child items because sorting order is determined by comparing rows. Therefore, `useSortBy` will have to be placed after `useExpanded`.

This allows for two behaviours:

* If `useSortBy` is placed after `useExpanded`, expanded items should be sorted. `useSortBy` can account for subRow levels and only sort within each level, i.e. we assume that all adjacent rows with equal level will always have the same parentRow. This ensures that expanded rows are not detached from their parent rows. The performance impact should not be a concern.
* If `useExpanded` is placed after `useSortBy`, then expanded items will not be sorted.

**Comment by Gildedter** [comment]
Any plans for `expandedRow` but without a `subRow`? I need to render a table within an `expandedRow`, its possible when using [svelte-table](https://github.com/hurtigruten/svelte-table), but I'm migrating to this for the `tableFilter` plugin

**Comment by bryanmylee** [comment]
> Any plans for `expandedRow` but without a `subRow`? I need to render a table within an `expandedRow`, its possible when using [svelte-table](https://github.com/hurtigruten/svelte-table), but I'm migrating to this for the `tableFilter` plugin

@Gildedter I've just taken a look at the example from svelte-table, and it seems like what you're looking for isn't really row expansion but rather labelling rows.

While I had plans to introduce a `addRowLabel` plugin, I felt like the ergonomics weren't up to par.

What you could do instead is to use `addSubRows`, but include a property like `type` on the data items that indicate the type of row to display.

```svelte
<script>
  /**
  Include a 'type' field on each data item i.e. 'data' and 'detail'.
  If you're using TypeScript, this can be used for a discriminated union – https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions
  Have a structure like:
  [
    {
      type: 'data',
      ...
      detail: [
        { type: 'detail', ... },
      ],
    },
  ]
  */
  const data = writable([...]);
  const table = createTable(data, {
    detail: addSubRows({ children: 'detail' }),
    expand: addExpandedRows(),
  });
  const { visibleColumns, headerRows, rows } = table.createViewModel(columns);
  ...
</script>
...
{#each $rows as row (row.id)}
  <Subscribe rowAttrs={row.attrs()} let:rowAttrs>
    <tr {...rowAttrs}>
      <!-- check if row is data or detail -->
      {#if row.original.type === 'data'}
        {#each row.cells as cell (cell.id)}
          <Subscribe attrs={cell.attrs()} let:attrs>
            <td {...attrs}>
              <Render of={cell.render()} />
            </td>
          </Subscribe>
        {/each}
      {:else if row.original.type === 'detail'}
        <!-- insert your custom logic / handling here -->
        <td colspan={$visibleColumns.length}>
          <Details data={row.original} />
        </td>
      {/if}
    </tr>
  </Subscribe>
{/each}
```
