### ISSUE TITLE
Examples site 404

### ISSUE THREAD

**Issue by gyurielf** [bryanmylee/svelte-headless-table#92]
Hey there!

Seems to something went wrong around the site.
![image](https://user-images.githubusercontent.com/12744391/209151842-e2285133-a6d5-4a14-9e86-6795916a45e1.png)

**Comment by bryanmylee** [comment]
Sorry about that, there's an issue with my current documentation framework [KitDocs](https://github.com/svelteness/kit-docs/pull/69) and Vercel.

I've rolled back the site to a previous version.

**Comment by gyurielf** [comment]
No problem, thanks for the fix.
