### ISSUE TITLE
Cell Event Dispatcher Isn't Reactive

### ISSUE THREAD

**Issue by risalfajar** [bryanmylee/svelte-headless-table#93]
I have this code which worked perfectly except the **Edit** button

```typescript
const repository = new UserRepository()
const data: Readable<User[]> = readable([], function start(set: Subscriber<User[]>) {
    return repository.listenAll(users => set(users ?? []))
})
const table = createTable(data)
const columns = table.createColumns([
    table.column({
        header: 'Username',
        accessor: 'username'
    }),
    table.column({
        id: 'actions',
        header: 'Actions',
        accessor: (item) => item,
        cell: ({value}, state) => createRender(TableActions)
            .on('edit', () => console.log(value.username))
    })
])
```

When a user click on edit button inside TableActions component, it'll trigger the `edit` event. The problem is when data changes, the username that gets printed on the console is not changed, it always printed the old value unless I refresh the page.

**Workaround**
```ts
    cell: (cell, state) => createRender(TableActions)
        .on('edit', () => console.log(get(state.data)[cell.row.id].username))
```

**Comment by bryanmylee** [comment]
Hey @risalfajar!

The event isn't reactive because you're passing a closure that captures the current value of `value.username` when the closure is defined.

Can you try passing `value` into `TableActions` as a prop, then using that value in the event handler?

```svelte
<!-- App.svelte -->
  cell: ({value}, state) => createRender(TableActions, {username: value.username})
    .on('edit', (ev) => console.log(ev.detail.username),
```

```svelte
<!-- TableActions.svelte -->
<script lang="ts">
  ...
  export let username: string;

  const handleClick = () => {
    dispatch('edit', {username});
  };
</script>
```

**Comment by bryanmylee** [comment]
I'm not too sure about this myself, but you could try capturing an object in the closure instead of the username primitive.

```ts
  cell: ({value}, state) => createRender(TableActions)
    .on('edit', () => {
      const captured = value;
      console.log(captured.value);
    }),
```

**Comment by risalfajar** [comment]
Sorry but It doesn't work

**Comment by amr3k** [comment]
I couldn't get the table to be reactive by using `$: tableData ...`, but instead I had to force re-render the table component itself from the parent using `{#key data}`.

**Comment by risalfajar** [comment]
@amr3k you're re-rendering the entire table which is too much IMO. You can use my workaround above.

**Comment by amr3k** [comment]
> @amr3k you're re-rendering the entire table which is too much IMO. You can use my workaround above.

I also have buttons and when I found this issue was not yet resolved, I decided to re-render the whole thing!

**Comment by bryanmylee** [comment]
I've added some documentation on the README highlighting the fact that `.on` is not reactive, so any data accessed from the handler has to be wrapped in a reactivity mechanism like a store.
