### ISSUE TITLE
v0.17.0 seems to break sorting

### ISSUE THREAD

**Issue by Sinderella** [bryanmylee/svelte-headless-table#96]
At least on REPL examples and my environment, sorting doesn't seem to work when clicked on the columns. Not sure if it affects other things as I just started trying things out.

https://svelte.dev/repl/457c10b649cc4bc7a84f9511a81b5361?version=3.48.0

Downgrading to 0.16.2 does make it work on my environment.

**Comment by AlexBitsTech** [comment]
Same thing for me.
The sorting works on v0.16.2 but not on the latest version.
